### ISSUE TITLE
Uninitialized Constant Spree::ReviewSetting (NameError) in Rails 7

### ISSUE THREAD

**Issue by edmondchui** [spree-contrib/spree_reviews#200]
Got the following error after upgrading the system to Rail 7

```
~/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/bundler/gems/spree_reviews-c3069ddb8026/lib/spree_reviews/engine.rb:13:in `block in <class:Engine>': uninitialized constant Spree::ReviewSetting (NameError)

      Spree::Reviews::Config = Spree::ReviewSetting.new
                                    ^^^^^^^^^^^^^^^
Did you mean?  Spree::Reviews
	from ~/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/railties-7.0.7.2/lib/rails/initializable.rb:32:in `instance_exec'
	from ~/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/railties-7.0.7.2/lib/rails/initializable.rb:32:in `run'
	from ~/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/railties-7.0.7.2/lib/rails/initializable.rb:61:in `block in run_initializers'
	from ~/.rbenv/versions/3.2.2/lib/ruby/3.2.0/tsort.rb:228:in `block in tsort_each'
	from ~/.rbenv/versions/3.2.2/lib/ruby/3.2.0/tsort.rb:350:in `block (2 levels) in each_strongly_connected_component'
	from ~/.rbenv/versions/3.2.2/lib/ruby/3.2.0/tsort.rb:422:in `block (2 levels) in each_strongly_connected_component_from'
	from ~/.rbenv/versions/3.2.2/lib/ruby/3.2.0/tsort.rb:431:in `each_strongly_connected_component_from'
	from ~/.rbenv/versions/3.2.2/lib/ruby/3.2.0/tsort.rb:421:in `block in each_strongly_connected_component_from'
	from ~/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/railties-7.0.7.2/lib/rails/initializable.rb:50:in `each'
	from ~/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/railties-7.0.7.2/lib/rails/initializable.rb:50:in `tsort_each_child'
	from ~/.rbenv/versions/3.2.2/lib/ruby/3.2.0/tsort.rb:415:in `call'
	from ~.rbenv/versions/3.2.2/lib/ruby/3.2.0/tsort.rb:415:in `each_strongly_connected_component_from'
	from ~/.rbenv/versions/3.2.2/lib/ruby/3.2.0/tsort.rb:349:in `block in each_strongly_connected_component'
	from ~/.rbenv/versions/3.2.2/lib/ruby/3.2.0/tsort.rb:347:in `each'
	from ~/.rbenv/versions/3.2.2/lib/ruby/3.2.0/tsort.rb:347:in `call'
	from ~/.rbenv/versions/3.2.2/lib/ruby/3.2.0/tsort.rb:347:in `each_strongly_connected_component'
	from ~/.rbenv/versions/3.2.2/lib/ruby/3.2.0/tsort.rb:226:in `tsort_each'
	from ~/.rbenv/versions/3.2.2/lib/ruby/3.2.0/tsort.rb:205:in `tsort_each'
	from ~/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/railties-7.0.7.2/lib/rails/initializable.rb:60:in `run_initializers'
	from ~/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/railties-7.0.7.2/lib/rails/application.rb:372:in `initialize!'
	from ~Development/Mobolet/mobolet_server/config/environment.rb:5:in `<top (required)>'
	from <internal:~/.rbenv/versions/3.2.2/lib/ruby/site_ruby/3.2.0/rubygems/core_ext/kernel_require.rb>:38:in `require'
	from <internal:~/.rbenv/versions/3.2.2/lib/ruby/site_ruby/3.2.0/rubygems/core_ext/kernel_require.rb>:38:in `require'
	from ~/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/polyglot-0.3.5/lib/polyglot.rb:65:in `require'
	from ~/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/zeitwerk-2.6.11/lib/zeitwerk/kernel.rb:38:in `require'
	from ~/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/railties-7.0.7.2/lib/rails/application.rb:348:in `require_environment!'
	from ~benv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/railties-7.0.7.2/lib/rails/command/actions.rb:28:in `require_environment!'
	from ~/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/railties-7.0.7.2/lib/rails/command/actions.rb:15:in `require_application_and_environment!'
	from ~/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/railties-7.0.7.2/lib/rails/commands/generate/generate_command.rb:21:in `perform'
	from ~/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/thor-1.2.2/lib/thor/command.rb:27:in `run'
	from ~/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/thor-1.2.2/lib/thor/invocation.rb:127:in `invoke_command'
	from ~/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/thor-1.2.2/lib/thor.rb:392:in `dispatch'
	from ~/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/railties-7.0.7.2/lib/rails/command/base.rb:87:in `perform'
	from ~/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/railties-7.0.7.2/lib/rails/command.rb:48:in `invoke'
	from ~/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/railties-7.0.7.2/lib/rails/commands.rb:18:in `<top (required)>'
	from <internal:~/rbenv/versions/3.2.2/lib/ruby/site_ruby/3.2.0/rubygems/core_ext/kernel_require.rb>:38:in `require'
	from <internal:~/.rbenv/versions/3.2.2/lib/ruby/site_ruby/3.2.0/rubygems/core_ext/kernel_require.rb>:38:in `require'
	from bin/rails:8:in `<main>'
```

**Comment by edmondchui** [comment]
Seems resolved in the latest version for Spree 4.5 support.
